language: node_js
matrix:
  fast_finish: true
node_js:
- '6'
branches:
  except:
  - build
env:
  global:
  - CXX=g++-4.8
  - secure: OnT+4EKE7IHu+1C/KTFpbsNJiD2fTM9bEfLxytIjSH35n8iWZyGdHLBlVrUulKLw47ir+g8T/FmEVJ9u+JSfYaq25oSoPUrcdW8Qs7RA+lg4W7LWGFXQeDaDC7KS1dRxQDc4eaRxfmbyDNEQG3HwsVbcaZXCrZQmwLGj5NWAseblvshLkhpYrdeMYIt+JUod63VUskdq8FVzm9AuFxBA1Ut4rwyX3wou5TDZMAgYwf1rlveAxkmZhYQQlt4j7Hyb5zT/K1S+zXKm4H+pqA/tvSbSRIw5JKFRf2tywom2Tn87BJ8mxYuMA2ANnsQ4c3jeJgQCNOk4oG5gUbPOa+JCN6RehHrsiGROExK0UY/e1uxFJfgyLmONBppJMFWO8Cn6Qxz5WQnrm/a5sE2RbZg+UuLi3WJIK6+yb/8P9XBPmZauBDLE6EOtUtx15Ti8WPZfuAbEBnJ7Q9gJv/5fpiMrgaYniohgU8cNs5qN6BsA/8JiY/f3lcVjLsPP4x+j0NzqKcUEXbMjXMGHWaQK/fizlcTH6moL8unlLNKkEmLEtg4w1x4cj3jvBMOiZsOfsGugqu0ZS2YRJqjpImVUThuPRoQkASR8mpq33PGXjBcKMPBol4K7c8DNrWKmwI1wgq/dl82wBDGIA3kAL6lrh4fBqzck2yqLrCdgH1MmolF14dI=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - deadsnakes
    packages:
    - g++-4.8
    - python3.5
cache:
  yarn: true
  directories:
  - node_modules
before_install:
- curl -fsSL https://bootstrap.pypa.io/get-pip.py | python3.5 - --user
- travis_retry pip3.5 install --user transifex-client
- install -m0644 .transifexrc.tpl ~/.transifexrc
- echo "password = $TX_PASSWD" >> ~/.transifexrc
- yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script:
- yarn test
- yarn build:browser
after_script: greenkeeper-lockfile-upload
after_success:
- test $TRAVIS_BRANCH = "master" && yarn run deploy --branch=build
